language: generic

env:
  global:
    # packages to install before ours go here
    - APM_TEST_PACKAGES="hyperclick linter"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      ATOM_CHANNEL: stable
      deploy:
        on:
          branch: master
        provider: script
        skip_cleanup: true
        before_script:
          - echo $PATH
          - apm -v
        script:
          - npx semantic-release

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - export PATH=$PATH:~/atom/usr/bin
  # - echo $PATH


script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

after_success:
  - apm -v

after_failure:
  - echo $PATH
